spring:
  mongodb:
    embedded:
      version: 3.5.5
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
      username: user
      password: user123
      authentication-database: admin
