spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true
  mongodb:
    embedded:
      version: 3.5.5
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
      username: user
      password: user123
      authentication-database: admin
  flyway:
    enabled: true
  jpa:
    show-sql: true
