spring:
  application:
    name: library-service
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

hystrix:
  command:
    getBooksData:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000




