version: '3.8'

services:

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: otus
      POSTGRES_PASSWORD: otus123
      POSTGRES_DB: otus
    ports:
      - "54321:5432"

  app:
    build: ./
    image: backend
    environment:
      SPRING_APP_PROFILE: prod
      JAVA_OPTIONS: "-Xmx512m"
    depends_on:
      - postgres
    ports:
      - "8080:8080"